before_script:
  - "psql -c 'create database socialite_test;' -U postgres >/dev/null"
  - "mysql -e 'create database socialite_test;' >/dev/null"
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
